//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronCloud.Atpc.Co.WPF.RecursosComunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Modelos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modelos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronCloud.Atpc.Co.WPF.RecursosComunes.Modelos", typeof(Modelos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cita.
        /// </summary>
        public static string Cita_Descripcion_Caption {
            get {
                return ResourceManager.GetString("Cita_Descripcion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string General_Codigo_Caption {
            get {
                return ResourceManager.GetString("General_Codigo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico esta mal escrito..
        /// </summary>
        public static string General_InvalidEmail {
            get {
                return ResourceManager.GetString("General_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario o Contraseña Incorrectos..
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta el nombre de usuario..
        /// </summary>
        public static string Login_NombreDeUsuario_Required {
            get {
                return ResourceManager.GetString("Login_NombreDeUsuario_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio.
        /// </summary>
        public static string Osc_Convenio_Caption {
            get {
                return ResourceManager.GetString("Osc_Convenio_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostico.
        /// </summary>
        public static string Osc_Diagnostico_Caption {
            get {
                return ResourceManager.GetString("Osc_Diagnostico_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Osc_Fecha_Caption {
            get {
                return ResourceManager.GetString("Osc_Fecha_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Anulación.
        /// </summary>
        public static string Osc_FechaAnulacion_Caption {
            get {
                return ResourceManager.GetString("Osc_FechaAnulacion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Registro.
        /// </summary>
        public static string Osc_FechaRegistro_Caption {
            get {
                return ResourceManager.GetString("Osc_FechaRegistro_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de OSC.
        /// </summary>
        public static string Osc_NumeroDocumento_Caption {
            get {
                return ResourceManager.GetString("Osc_NumeroDocumento_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Osc_Observaciones_Caption {
            get {
                return ResourceManager.GetString("Osc_Observaciones_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestador.
        /// </summary>
        public static string Osc_Prestador_Caption {
            get {
                return ResourceManager.GetString("Osc_Prestador_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitente.
        /// </summary>
        public static string Osc_Remitente_Caption {
            get {
                return ResourceManager.GetString("Osc_Remitente_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuló.
        /// </summary>
        public static string Osc_UsuarioAnulacion_Caption {
            get {
                return ResourceManager.GetString("Osc_UsuarioAnulacion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Creación.
        /// </summary>
        public static string Osc_UsuarioCreacion_Caption {
            get {
                return ResourceManager.GetString("Osc_UsuarioCreacion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Pais_Codigo_Caption {
            get {
                return ResourceManager.GetString("Pais_Codigo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código del Pais.
        /// </summary>
        public static string Pais_Codigo_Description {
            get {
                return ResourceManager.GetString("Pais_Codigo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Pais_Nombre_Caption {
            get {
                return ResourceManager.GetString("Pais_Nombre_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Pais.
        /// </summary>
        public static string Pais_Nombre_Descripcion {
            get {
                return ResourceManager.GetString("Pais_Nombre_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Máximo de Resultados.
        /// </summary>
        public static string ParametrosBusqueda_NumeroDeResultados_Caption {
            get {
                return ResourceManager.GetString("ParametrosBusqueda_NumeroDeResultados_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número OSC.
        /// </summary>
        public static string ParametrosBusqueda_NumeroOsc_Caption {
            get {
                return ResourceManager.GetString("ParametrosBusqueda_NumeroOsc_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Paciente.
        /// </summary>
        public static string ParametrosBusqueda_NumeroUnicoDocumento_Caption {
            get {
                return ResourceManager.GetString("ParametrosBusqueda_NumeroUnicoDocumento_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string PersonalAsistencial_Codigo_Caption {
            get {
                return ResourceManager.GetString("PersonalAsistencial_Codigo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        public static string PersonalAsistencial_Nombre_Caption {
            get {
                return ResourceManager.GetString("PersonalAsistencial_Nombre_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesión.
        /// </summary>
        public static string PersonalAsistencial_Profesion_Caption {
            get {
                return ResourceManager.GetString("PersonalAsistencial_Profesion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrio.
        /// </summary>
        public static string Tercero_Barrio_Caption {
            get {
                return ResourceManager.GetString("Tercero_Barrio_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Tercero_Direccion_Caption {
            get {
                return ResourceManager.GetString("Tercero_Direccion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Corporativo.
        /// </summary>
        public static string Tercero_EmailEmpresa_Caption {
            get {
                return ResourceManager.GetString("Tercero_EmailEmpresa_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Personal.
        /// </summary>
        public static string Tercero_EmailPersonal_Caption {
            get {
                return ResourceManager.GetString("Tercero_EmailPersonal_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Tercero_Fax_Caption {
            get {
                return ResourceManager.GetString("Tercero_Fax_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string Tercero_FechaNacimiento_Caption {
            get {
                return ResourceManager.GetString("Tercero_FechaNacimiento_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Tercero_Genero_Caption {
            get {
                return ResourceManager.GetString("Tercero_Genero_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        public static string Tercero_NombreCompleto_Caption {
            get {
                return ResourceManager.GetString("Tercero_NombreCompleto_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de Documento.
        /// </summary>
        public static string Tercero_NumeroDocumento_Caption {
            get {
                return ResourceManager.GetString("Tercero_NumeroDocumento_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Apellido.
        /// </summary>
        public static string Tercero_PrimerApellido_Caption {
            get {
                return ResourceManager.GetString("Tercero_PrimerApellido_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Nombre.
        /// </summary>
        public static string Tercero_PrimerNombre_Caption {
            get {
                return ResourceManager.GetString("Tercero_PrimerNombre_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido.
        /// </summary>
        public static string Tercero_SegundoApellido_Caption {
            get {
                return ResourceManager.GetString("Tercero_SegundoApellido_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Nombre.
        /// </summary>
        public static string Tercero_SegundoNombre_Caption {
            get {
                return ResourceManager.GetString("Tercero_SegundoNombre_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Alterno.
        /// </summary>
        public static string Tercero_TelefonoAlterno_Caption {
            get {
                return ResourceManager.GetString("Tercero_TelefonoAlterno_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Tercero_TelefonoMovil_Caption {
            get {
                return ResourceManager.GetString("Tercero_TelefonoMovil_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Residencia.
        /// </summary>
        public static string Tercero_TelefonoResidencia_Caption {
            get {
                return ResourceManager.GetString("Tercero_TelefonoResidencia_Caption", resourceCulture);
            }
        }
    }
}
